#公共配置
server:
    port: 8080

#数据库连接池
druid:
    type: com.alibaba.druid.pool.DruidDataSource
    readSize : 2
    master:
        url: jdbc:mysql://192.168.50.54:3307/wgoa_master?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        driver-class-name: com.mysql.jdbc.Driver
        username: mysql
        password: oa123456
        initial-size: 5
        min-idle: 1
        max-active: 100
        test-on-borrow: true
    slave:
        url: jdbc:mysql://192.168.50.54:3307/wgoa_slave?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: mysql
        password: oa123456
        initial-size: 5
        min-idle: 1
        max-active: 100
        test-on-borrow: true
    slave2:
        url: jdbc:mysql://192.168.50.54:3307/wgoa_slave?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: mysql
        password: oa123456
        initial-size: 5
        min-idle: 1
        max-active: 100
        test-on-borrow: true